export const SET_CLIENTS = "SET_CLIENTS";
// Actions for register page
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const SET_HEALTH_DETAILS = "SET_HEALTH_DETAILS";
export const SET_PROCESSING = "SET_PROCESSING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const AUTH_FAIL = "AUTH_FAIL";
export const LOGIN_LOAD = "LOGIN_LOAD";
export const LOGOUT = "LOGOUT";
